# Generated by Django 5.1.6 on 2025-02-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(help_text='Enter message.')),
                ('photos', models.CharField(blank=True, max_length=255, null=True)),
                ('question_text', models.TextField(help_text='Enter question text.')),
                ('options', models.TextField(help_text='Enter options separated by newlines.')),
                ('answer', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
