# Generated by Django 5.1.6 on 2025-03-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.FileField(null=True, upload_to='questions'),
        ),
    ]
