# Generated by Django 5.1.6 on 2025-04-03 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_question_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(help_text="Correct option (e.g., 'a', 'b', 'c', 'd')", max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation for the correct answer', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='questions/pictures'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(help_text='Enter option text')),
                ('option_letter', models.CharField(help_text="Option identifier (e.g., 'a', 'b', 'c', 'd')", max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question')),
            ],
        ),
    ]
