# Generated by Django 5.1.6 on 2025-04-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_remove_question_messages_remove_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dificulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', help_text='Select difficulty level', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='photo_caption',
            field=models.TextField(blank=True, help_text='Caption of the photo', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='photo_spoiler',
            field=models.TextField(blank=True, help_text='Spoiler text for the photo', null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_letter',
            field=models.CharField(help_text="Option identifier (e.g., 'a', 'b', 'c', 'd')", max_length=3),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='options', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(help_text="Correct option (e.g., 'a', 'b', 'c', 'd')", max_length=3),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(help_text='Enter message text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='questions.question')),
            ],
        ),
    ]
