# Generated by Django 5.1.6 on 2025-04-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_question_dificulty_question_photo_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_letter',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], help_text='Select option letter', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], help_text='Select option letter', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='photo_spoiler',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Spoiler text for the photo'),
        ),
    ]
