# Generated by Django 5.1.6 on 2025-04-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_option_option_letter_alter_question_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, help_text='Hint for the question', null=True),
        ),
    ]
