# Generated by Django 5.1.6 on 2025-04-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='option_letter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(choices=[(True, 'Yes')], default=False, help_text='Is this option correct?', max_length=1),
        ),
    ]
