# Generated by Django 5.1.6 on 2025-04-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_remove_option_option_letter_remove_question_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.AddField(
            model_name='question',
            name='short_explanation',
            field=models.CharField(blank=True, help_text='Max characters: 200', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this option correct?', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.CharField(help_text='Max characters: 100', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(help_text='Max characters: 300', max_length=300),
        ),
    ]
