# Generated by Django 5.1.6 on 2025-06-11 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_remove_question_explanation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Max characters: 30', max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='dificulty',
            new_name='difficulty',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(help_text='Max characters: 500', max_length=500),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.TextField(help_text='Max characters: 100', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='photo_caption',
            field=models.TextField(blank=True, help_text='Max characters: 300', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='Max characters: 300', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='short_explanation',
            field=models.TextField(blank=True, help_text='Max characters: 200', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.category'),
        ),
    ]
