# Generated by Django 4.2.23 on 2025-12-07 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_alter_message_question_alter_option_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.category'),
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(help_text='Paste your source code here')),
                ('language', models.CharField(default='java', max_length=50)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippet', to='questions.question')),
            ],
        ),
    ]
