# Generated by Django 4.2.23 on 2025-12-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_alter_question_category_codesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
