# Generated by Cascade on demand
from django.db import migrations, models


def backfill_titles(apps, schema_editor):
    Question = apps.get_model('questions', 'Question')
    # Ensure any empty titles (if any) are set to 'No title'
    Question.objects.filter(title='').update(title='No title')


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_add_ready_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100, default='No title'),
        ),
        migrations.RunPython(backfill_titles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
