services:
  - type: web
    name: quizzleef-app
    env: python
    buildCommand: "./manage.py collectstatic --noinput"
    startCommand: "gunicorn quizzleef.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: quizzleef-app.onrender.com
